vim.api.nvim_set_keymap('n', '<F8>', ':Files<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('', '<F3>', ':BufferLineCycleNext<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('', '<F4>', ':BufferLineCyclePrev<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-n>', ':NvimTreeToggle<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-d>', "<cmd>lua require('lspsaga.hover').render_hover_doc()<CR>", {noremap = true})
vim.api.nvim_set_keymap('n', '<F5>', ':Lspsaga open_floaterm<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<C-t>', ':FloatermNew<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<C-x>', ':FloatermKill<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-b>', ":lua require('lspsaga.floaterm').close_float_terminal()<CR>", {noremap = true})
