vim.api.nvim_set_keymap('n', '<F8>', ':Files<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('', '<C-r>', ':RustRunnables<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('', 'gh', ":lua require'lspsaga.provider'.lsp_finder()<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-n>', ':NvimTreeToggle<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-d>', ":Telescope find_files<CR>", {noremap = true})
vim.api.nvim_set_keymap('n', 'C-x', ':Lspsaga close_floaterm<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<C-t>', '::Lspsaga open_floaterm<CR>', {noremap = true})
vim.api.nvim_set_keymap('', 'gd', ':Lspsaga preview_definition<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', 'gr', ":lua require('lspsaga.rename').rename()<CR>", {noremap = true})
